version: '3.8'
services:
  tomcat:
    container_name: tomcat
    image: tomcat
    ports:
      - "8080:8080"
    volumes:
      - ./webapps.dist:/usr/local/tomcat/webapps/
      - ./webapps2:/usr/local/tomcat/webapps2/
      - ./conf:/usr/local/tomcat/conf/
